NEW_TODO = "//input[@class='new-todo']"
EDIT_TODO = "//input[@class='edit']"
EXISTING_TODO = "//label[@can-dblclick='edit' and text()='{}']"
TODO_LIST = "//input[@class='edit' and @can-enter = 'updateTodo']"
ACTIVE_TODO_LIST = "//ul[@class='todo-list']/li[@class='todo']//label"
COMPLETED_TODO_LIST = "//ul[@class='todo-list']/li[@class='todo completed']//label"
TOGGLE = "//li[div/label[text()='{}']]/div/input[@class='toggle']"
DELETE = "//li[div/label[text()='{}']]/div/button[@class='destroy']"
CLEAR_COMPLETED = "//button[@can-click='clearCompleted']"
ITEMS_LEFT = "//span[@class='todo-count']/strong"

filter_ = "//ul[@class='filters']//a[@href='#!{}']"
activate = " and @class='selected'"
ACTIVE_FILTER = "//ul[@class='filters']//a[@class='selected']"
